#! /bin/bash

# This ensures globbing is enabled
set +f

# Get the absolute path to this script directory
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
ABSOLUTE_SCRIPT_DIR=$(realpath "$SCRIPT_DIR")

# Use that to make the absolute path for a post building node module
BUILD_POST_SCRIPT="${ABSOLUTE_SCRIPT_DIR}/build_post.js"

# also use that to get the absolute path of our src blogs
SRC_DIR="${ABSOLUTE_SCRIPT_DIR}/../src/blog"

for BLOG_POST_DIR in "$SRC_DIR"/*; do
  echo "building ${BLOG_POST_DIR}"
  node "${BUILD_POST_SCRIPT}" \
    -i $BLOG_POST_DIR \
    -o dist/blog \
    -a dist/assets/blog
done
