#! /bin/bash

# This ensures globbing is enabled
set +f

# Get the absolute path to this script directory
SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}")
ABSOLUTE_SCRIPT_DIR=$(realpath "$SCRIPT_DIR")

# Use that to make the absolute path for a post building node module
BUILD_WORKING_NOTE_SCRIPT="${ABSOLUTE_SCRIPT_DIR}/build_post.js"

# also use that to get the absolute path of our src blogs
SRC_DIR="${ABSOLUTE_SCRIPT_DIR}/../src/working-notes"

for WORKING_NOTE_DIR in "$SRC_DIR"/*; do
  echo "building ${WORKING_NOTE_DIR}"
  node "${BUILD_WORKING_NOTE_SCRIPT}" \
    -i "${WORKING_NOTE_DIR}" \
    -o dist/working-notes \
    -a dist/assets/working-notes \
    -s dist/global-styles.css \
    --is-note
done
